### ISSUE TITLE
On the  Select role section it better if it set default state to Frontend ?

### ISSUE THREAD

**Issue by 22p21s0045** [Hello-Goose/Hello-Goose#29]
![image](https://github.com/Hello-Goose/Hello-Goose/assets/71715345/13994eae-a5b8-4dfd-8785-508b9e0079e7)

On this section first load default state is none what do you think if set default state to Frontend role I think it make UX better.

![image](https://github.com/Hello-Goose/Hello-Goose/assets/71715345/21063706-26db-435c-b621-ee1e4731b262)

**Comment by bestzige** [comment]
Resolved
